{{- if .Values.podDisruptionBudget.gateway.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "section.componentName" (dict "ctx" . "component" "gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "section.componentLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.gateway.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.gateway.minAvailable }}
  {{- else if .Values.podDisruptionBudget.gateway.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.gateway.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "section.componentSelectorLabels" (dict "ctx" . "component" "gateway") | nindent 6 }}
{{- end }}
