apiVersion: v1
kind: Service
metadata:
  name: {{ include "section.componentName" (dict "ctx" . "component" "gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "section.componentLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
  {{- with .Values.service.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gateway.type }}
  ports:
    - name: http
      port: {{ .Values.service.gateway.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "section.componentSelectorLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "section.componentName" (dict "ctx" . "component" "gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "section.componentLabels" (dict "ctx" . "component" "gateway") | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "section.componentSelectorLabels" (dict "ctx" . "component" "gateway") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
