apiVersion: v1
kind: Service
metadata:
  name: {{ include "section.componentName" (dict "ctx" . "component" "ui") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "section.componentLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
  {{- with .Values.service.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - name: http
      port: {{ .Values.service.ui.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "section.componentSelectorLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
