{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "praesidio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "praesidio.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts.gateway }}
    - host: {{ .Values.ingress.hosts.gateway | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "praesidio.componentName" (dict "ctx" . "component" "gateway") }}
                port:
                  number: {{ .Values.service.gateway.port }}
    {{- end }}
    {{- if .Values.ingress.hosts.ui }}
    - host: {{ .Values.ingress.hosts.ui | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "praesidio.componentName" (dict "ctx" . "component" "ui") }}
                port:
                  number: {{ .Values.service.ui.port }}
    {{- end }}
{{- end }}
