{{- if .Values.redis.embedded }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "praesidio.componentName" (dict "ctx" . "component" "redis") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "praesidio.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "praesidio.componentSelectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
{{- end }}
