{{- if .Values.podDisruptionBudget.ui.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "praesidio.componentName" (dict "ctx" . "component" "ui") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "praesidio.componentLabels" (dict "ctx" . "component" "ui") | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.ui.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.ui.minAvailable }}
  {{- else if .Values.podDisruptionBudget.ui.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.ui.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "praesidio.componentSelectorLabels" (dict "ctx" . "component" "ui") | nindent 6 }}
{{- end }}
