"""Prometheus metrics. Mounted at /metrics."""
from __future__ import annotations

from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram, generate_latest
from prometheus_client.exposition import CONTENT_TYPE_LATEST

# Use a dedicated registry so tests don't trip "Duplicated timeseries" on import.
REGISTRY = CollectorRegistry(auto_describe=True)

REQUEST_TOTAL = Counter(
    "section_request_total",
    "Total inbound requests.",
    labelnames=("route", "method", "status"),
    registry=REGISTRY,
)

DECISION_TOTAL = Counter(
    "section_decision_total",
    "Policy decisions emitted.",
    labelnames=("decision", "policy_id", "tenant"),
    registry=REGISTRY,
)

DETECTOR_LATENCY = Histogram(
    "section_detector_latency_seconds",
    "Per-detector wall-clock latency.",
    labelnames=("detector",),
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
    registry=REGISTRY,
)

VAULT_OPS_TOTAL = Counter(
    "section_vault_ops_total",
    "Token vault operations.",
    labelnames=("op", "outcome"),
    registry=REGISTRY,
)

UPSTREAM_LATENCY = Histogram(
    "section_upstream_latency_seconds",
    "Upstream provider latency.",
    labelnames=("provider", "model"),
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0),
    registry=REGISTRY,
)

AUDIT_WRITE_TOTAL = Counter(
    "section_audit_write_total",
    "Audit rows written.",
    labelnames=("outcome",),
    registry=REGISTRY,
)

POLICY_RELOAD_TOTAL = Counter(
    "section_policy_reload_total",
    "Policy bundle reloads attempted.",
    labelnames=("outcome",),
    registry=REGISTRY,
)

DETECTOR_BREAKER_OPENS_TOTAL = Counter(
    "section_detector_breaker_opens_total",
    "Times a detector circuit breaker opened.",
    labelnames=("detector",),
    registry=REGISTRY,
)

RATE_LIMIT_BLOCKED_TOTAL = Counter(
    "section_rate_limit_blocked_total",
    "Requests rejected by the token-bucket rate limiter (any scope).",
    labelnames=("tenant", "scope"),
    registry=REGISTRY,
)

# G3: policy hot-reload observability
POLICY_ACTIVE_VERSION = Gauge(
    "section_policy_active_version",
    "Active policy bundle version; gauge value is a stable integer derived "
    "from the first 8 hex chars of the bundle digest. Inspect labels for the "
    "human-readable digest and policy count.",
    labelnames=("digest", "policies"),
    registry=REGISTRY,
)

# G5: token / cost metering
TOKENS_IN_TOTAL = Counter(
    "section_tokens_in_total",
    "Prompt (input) tokens consumed by upstream providers.",
    labelnames=("tenant", "model", "route"),
    registry=REGISTRY,
)

TOKENS_OUT_TOTAL = Counter(
    "section_tokens_out_total",
    "Completion (output) tokens generated by upstream providers.",
    labelnames=("tenant", "model", "route"),
    registry=REGISTRY,
)

COST_USD_TOTAL = Counter(
    "section_cost_usd_total",
    "Estimated upstream cost in USD (priced from obs/prices.py).",
    labelnames=("tenant", "model"),
    registry=REGISTRY,
)

# G6: tool-call allowlist enforcement
TOOL_CALLS_BLOCKED_TOTAL = Counter(
    "section_tool_calls_blocked_total",
    "Tool invocations rejected by the policy allowlist.",
    labelnames=("tenant", "policy", "tool"),
    registry=REGISTRY,
)


def render_metrics() -> tuple[bytes, str]:
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST
